# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJLrsglknmrdbqXqhu62Ok2ffdJPzfXt
"""

from flask import Flask, request, jsonify
import pickle
import pandas as pd

app = Flask(__name__)

# Load the saved model
model = pickle.load(open("model.pkl", "rb"))

@app.route('/')
def home():
    return "Coupon Redemption Prediction API is Live!"

@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = pd.DataFrame([request.json])
        prob = model.predict_proba(data)[0][1]
        return jsonify({'redemption_probability': round(prob, 4)})
    except Exception as e:
        return jsonify({'error': str(e)})